# Generated by Django 5.0.1 on 2024-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_carttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
